// <auto-generated />
using Kolos_Test.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Kolos_Test.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Kolos_Test.entities.Courses", b =>
                {
                    b.Property<int>("CourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CourseId"));

                    b.Property<int>("Credits")
                        .HasColumnType("int");

                    b.Property<int>("ProfessorId")
                        .HasColumnType("int");

                    b.Property<int>("Semester")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CourseId");

                    b.HasIndex("ProfessorId");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            CourseId = 1,
                            Credits = 283,
                            ProfessorId = 1,
                            Semester = 1,
                            Title = "Kurs dla cweli v1"
                        },
                        new
                        {
                            CourseId = 2,
                            Credits = 100,
                            ProfessorId = 2,
                            Semester = 4,
                            Title = "Kurs dla cweli v2"
                        });
                });

            modelBuilder.Entity("Kolos_Test.entities.Departments", b =>
                {
                    b.Property<int>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DepartmentId"));

                    b.Property<decimal>("Budget")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric");

                    b.Property<string>("FacultyBuilding")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("DepartmentId");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            DepartmentId = 1,
                            Budget = 1999.2m,
                            FacultyBuilding = "budynek dla cweli",
                            Name = "Kurs dla cweli v1"
                        },
                        new
                        {
                            DepartmentId = 2,
                            Budget = 3299.2m,
                            FacultyBuilding = "budynek dla cweli v2",
                            Name = "Kurs dla cweli v2"
                        });
                });

            modelBuilder.Entity("Kolos_Test.entities.Enrollments", b =>
                {
                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<decimal?>("Grade")
                        .HasPrecision(2, 1)
                        .HasColumnType("numeric");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CourseId", "StudentId");

                    b.HasIndex("StudentId");

                    b.ToTable("Enrollments");

                    b.HasData(
                        new
                        {
                            CourseId = 1,
                            StudentId = 1,
                            Grade = 5.3m,
                            Status = "chujnia"
                        },
                        new
                        {
                            CourseId = 2,
                            StudentId = 2,
                            Grade = 1.3m,
                            Status = "cyka nahui"
                        });
                });

            modelBuilder.Entity("Kolos_Test.entities.Professors", b =>
                {
                    b.Property<int>("ProfessorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProfessorId"));

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ProfessorId");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Professors");

                    b.HasData(
                        new
                        {
                            ProfessorId = 1,
                            DepartmentId = 1,
                            Email = "jestemcwelem@gmail.com",
                            FirstName = "ss",
                            LastName = "dsdsd"
                        },
                        new
                        {
                            ProfessorId = 2,
                            DepartmentId = 2,
                            Email = "jestemcwelem235@gmail.com",
                            FirstName = "fdff",
                            LastName = "dfsfds"
                        });
                });

            modelBuilder.Entity("Kolos_Test.entities.Students", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("EnrollmentId")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("StudentId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            StudentId = 1,
                            Email = "Cwelisko@chuj.pl",
                            EnrollmentId = 1,
                            FirstName = "cwel",
                            LastName = "cwelisko"
                        },
                        new
                        {
                            StudentId = 2,
                            Email = "pedal@cwel.pl",
                            EnrollmentId = 2,
                            FirstName = "pedal",
                            LastName = "pedalski"
                        });
                });

            modelBuilder.Entity("Kolos_Test.entities.Courses", b =>
                {
                    b.HasOne("Kolos_Test.entities.Professors", "Professors")
                        .WithMany("Courses")
                        .HasForeignKey("ProfessorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Professors");
                });

            modelBuilder.Entity("Kolos_Test.entities.Enrollments", b =>
                {
                    b.HasOne("Kolos_Test.entities.Courses", "Courses")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kolos_Test.entities.Students", "Students")
                        .WithMany("Enrollments")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Courses");

                    b.Navigation("Students");
                });

            modelBuilder.Entity("Kolos_Test.entities.Professors", b =>
                {
                    b.HasOne("Kolos_Test.entities.Departments", "Departments")
                        .WithMany("Professors")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Departments");
                });

            modelBuilder.Entity("Kolos_Test.entities.Departments", b =>
                {
                    b.Navigation("Professors");
                });

            modelBuilder.Entity("Kolos_Test.entities.Professors", b =>
                {
                    b.Navigation("Courses");
                });

            modelBuilder.Entity("Kolos_Test.entities.Students", b =>
                {
                    b.Navigation("Enrollments");
                });
#pragma warning restore 612, 618
        }
    }
}
